// ✅ 

// Description:
// A single file to implement multiple simple indicators.
// Always ignore the current (forming) candle and evaluate only completed candles.

// Indicators Implemented (1):
// - 3 candles each inside previous


//@version=6
indicator(title="Indicator Monolith", shorttitle="Ind Mono", overlay=true)

//*********************************************//
//                 INPUTS                      //
//*********************************************//
show_3cInside = input.bool(true, title="Show 3C Inside pattern")


//*********************************************//
//         HELPER FUNCTIONS                    //
//*********************************************//

// Use helper function for inside check (strict)
_inside(highChild, lowChild, highParent, lowParent) =>
	(highChild < highParent) and (lowChild > lowParent)


//*********************************************//
//           INDICATOR IMPLEMENTATIONS         //
//*********************************************//

// --- 3 candles each inside previous ---
//			Description:
//    		- 3 candles: next inside previous (lower high and higher low)

three_inside_indicator() =>
	// Define the three bars
	h3 = high[3], l3 = low[3]
	h2 = high[2], l2 = low[2]
	h1 = high[1], l1 = low[1]

	inside2in3 = _inside(h2, l2, h3, l3)
	inside1in2 = _inside(h1, l1, h2, l2)

	inside2in3 and inside1in2


//*********************************************//
//           CALL & DRAW INDICATORS            //
//*********************************************//

pattern_3cInside = three_inside_indicator()
plotshape(series=(show_3cInside and pattern_3cInside), title="3C Inside", style=shape.triangledown, location=location.abovebar, color=color.blue, size=size.tiny, text="3C Inside", offset=-1)